os: linux
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
  - "/home/travis/.cache/Cypress"
node_js:
- lts/*
- 10
before_install:
install:
- npm install
- npm install -g conventional-changelog-cli
- npm install -g conventional-github-releaser
- cypress install
before_script:
script:
- npm run build
- npm run test
after_success:
after_failure:
- ls -a
deploy:
  provider: npm
  email: wangnew2013@126.com
  api_key:
    secure: l1DfBx70F2wPxZpLLl7YHNoUevqht8stZm6KJrGS2INIE8rvpsHppjqW9DwYbXjZeYPQ5tPx3TWDXkPP2kM1A2XKLhk/hh2KSsvW01vB/oCOmsfdfJR2XHxwztLmoOgD+sLIVAiE5hJ7bJbcK1SPQWBswaf1NqPYSC+N2rGNTeuk5riGdb3dqOb6On5zkzfr71SQn0oEo8I827vmE5oF+8QfL/rgTWIbL/hovQkfX0GUASgozC4exbnT0DeMHyqNoFNdpPR6FdoeLUEn5KUxEC+Op08B3eff1Qg5j25XKlzoA8/4XF5NihskNw9Cw3e/uZ/ycFhiwp/ZiFANM31Z5COfkMBXaOiOQF/gmDQPK5yNYl3mtRuMvlhGm+J34DtN57HqCOQgDOM2iicrLAV1GSP+bNGNOMX7mzmqJPtu2kdEMAZIXg1FLQP/DSr3FwmSzhjxio8P8JSbdw2nVpZBHdCIfq4Kt9ALvSZRB7aDAWYDqOZ1iIxvSW9sR4wxPN41pOhzhSf3eRFmFxKWmu1cQfuowemvBOolmmg7YejPtVmGFegMlV1lxaHDzWQI9ZgAIVv6G7FVS2yBsWWElhV/WxBCQEq48gVwx52+oOI1d5mfpQ9KNBYZgoLsJ/gUB88J61jSE7FsiLF/MwlcVymhicDRbKp+y0C0Fe2JrcAuDak=
  on:
    tags: true
    repo: awamwang/vue-wangeditor-awesome
  skip_cleanup: 'true'
after_deploy:
- export CONVENTIONAL_GITHUB_RELEASER_TOKEN=$GH_TOKEN
- npm run github-release
